In [76]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [77]:
def read_csv(file_path):
    df = pd.read_csv(file_path)
    X = np.array(df["sentence"])
    Y = np.array(df["label"], dtype=int)
    return X, Y

In [78]:
X_train, Y_train = read_csv("/content/dataset/train.csv")
X_test, Y_test = read_csv("/content/dataset/test.csv")

In [79]:
index = 7
X_train[index], Y_train[index]

('congratulations on your acceptance', np.int64(2))

In [80]:
def label_to_emoji(label):
    emojies = ["❤️", "⚾", "😀", "😔", "🍴"]
    return emojies[label]

In [ ]:
index = 7
X_train[index], label_to_emoji(Y_train[index])

('congratulations on your acceptance', '😀')

In [ ]:
Y_train

array([3, 2, 3, 0, 4, 0, 3, 2, 3, 1, 3, 3, 1, 3, 2, 3, 2, 3, 1, 2, 3, 0,
       2, 2, 2, 1, 4, 2, 2, 4, 0, 3, 4, 2, 0, 3, 2, 2, 3, 4, 2, 2, 0, 2,
       3, 0, 3, 2, 4, 3, 0, 3, 3, 3, 4, 2, 1, 1, 1, 2, 3, 1, 0, 0, 0, 3,
       4, 4, 2, 2, 1, 2, 0, 3, 2, 2, 0, 0, 3, 1, 2, 1, 2, 2, 4, 3, 3, 2,
       4, 0, 0, 0, 3, 3, 3, 2, 0, 1, 2, 3, 0, 2, 2, 2, 3, 2, 2, 2, 4, 1,
       1, 3, 3, 4, 1, 2, 1, 1, 3, 1, 0, 4, 0, 3, 3, 4, 4, 1, 4, 3, 0, 2])

In [ ]:
np.unique(Y_train)

array([0, 1, 2, 3, 4])

In [ ]:
len(np.unique(Y_train))

5

In [ ]:
unique, counts = np.unique(Y_train, return_counts=True)
print(unique)
print(counts)

[0 1 2 3 4]
[22 19 38 36 17]


In [ ]:
max(X_train, key=len)

'I am so impressed by your dedication to this project'

In [ ]:
max(X_train, key=len).split(" ")

['I',
 'am',
 'so',
 'impressed',
 'by',
 'your',
 'dedication',
 'to',
 'this',
 'project']

In [ ]:
max_len = len(max(X_train, key=len).split(" "))
max_len

10

In [ ]:
!wget https://nlp.stanford.edu/data/glove.6B.zip

--2025-05-11 07:35:03--  https://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2025-05-11 07:35:03--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6B.zip        100%[===================>] 822.24M  5.01MB/s    in 2m 38s  

2025-05-11 07:37:42 (5.19 MB/s) - ‘glove.6B.zip’ saved [862182613/862182613]



In [ ]:
!unzip -q glove.6B.zip -d glove.6B