In [76]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [77]:
def read_csv(file_path):
    df = pd.read_csv(file_path)
    X = np.array(df["sentence"])
    Y = np.array(df["label"], dtype=int)
    return X, Y

In [78]:
X_train, Y_train = read_csv("/content/dataset/train.csv")
X_test, Y_test = read_csv("/content/dataset/test.csv")

In [79]:
index = 7
X_train[index], Y_train[index]

('congratulations on your acceptance', np.int64(2))

In [80]:
def label_to_emoji(label):
    emojies = ["❤️", "⚾", "😀", "😔", "🍴"]
    return emojies[label]

In [ ]:
index = 7
X_train[index], label_to_emoji(Y_train[index])

('congratulations on your acceptance', '😀')

In [ ]:
Y_train

array([3, 2, 3, 0, 4, 0, 3, 2, 3, 1, 3, 3, 1, 3, 2, 3, 2, 3, 1, 2, 3, 0,
       2, 2, 2, 1, 4, 2, 2, 4, 0, 3, 4, 2, 0, 3, 2, 2, 3, 4, 2, 2, 0, 2,
       3, 0, 3, 2, 4, 3, 0, 3, 3, 3, 4, 2, 1, 1, 1, 2, 3, 1, 0, 0, 0, 3,
       4, 4, 2, 2, 1, 2, 0, 3, 2, 2, 0, 0, 3, 1, 2, 1, 2, 2, 4, 3, 3, 2,
       4, 0, 0, 0, 3, 3, 3, 2, 0, 1, 2, 3, 0, 2, 2, 2, 3, 2, 2, 2, 4, 1,
       1, 3, 3, 4, 1, 2, 1, 1, 3, 1, 0, 4, 0, 3, 3, 4, 4, 1, 4, 3, 0, 2])

In [ ]:
np.unique(Y_train)

array([0, 1, 2, 3, 4])

In [ ]:
len(np.unique(Y_train))

5

In [ ]:
unique, counts = np.unique(Y_train, return_counts=True)
print(unique)
print(counts)

[0 1 2 3 4]
[22 19 38 36 17]


In [ ]:
max(X_train, key=len)

'I am so impressed by your dedication to this project'

In [ ]:
max(X_train, key=len).split(" ")

['I',
 'am',
 'so',
 'impressed',
 'by',
 'your',
 'dedication',
 'to',
 'this',
 'project']

In [ ]:
max_len = len(max(X_train, key=len).split(" "))
max_len

10