In [76]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [77]:
def read_csv(file_path):
    df = pd.read_csv(file_path)
    X = np.array(df["sentence"])
    Y = np.array(df["label"], dtype=int)
    return X, Y

In [78]:
X_train, Y_train = read_csv("/content/dataset/train.csv")
X_test, Y_test = read_csv("/content/dataset/test.csv")

In [79]:
index = 7
X_train[index], Y_train[index]

('congratulations on your acceptance', np.int64(2))

In [80]:
def label_to_emoji(label):
    emojies = ["❤️", "⚾", "😀", "😔", "🍴"]
    return emojies[label]

In [ ]:
index = 7
X_train[index], label_to_emoji(Y_train[index])

('congratulations on your acceptance', '😀')

In [ ]:
Y_train

array([3, 2, 3, 0, 4, 0, 3, 2, 3, 1, 3, 3, 1, 3, 2, 3, 2, 3, 1, 2, 3, 0,
       2, 2, 2, 1, 4, 2, 2, 4, 0, 3, 4, 2, 0, 3, 2, 2, 3, 4, 2, 2, 0, 2,
       3, 0, 3, 2, 4, 3, 0, 3, 3, 3, 4, 2, 1, 1, 1, 2, 3, 1, 0, 0, 0, 3,
       4, 4, 2, 2, 1, 2, 0, 3, 2, 2, 0, 0, 3, 1, 2, 1, 2, 2, 4, 3, 3, 2,
       4, 0, 0, 0, 3, 3, 3, 2, 0, 1, 2, 3, 0, 2, 2, 2, 3, 2, 2, 2, 4, 1,
       1, 3, 3, 4, 1, 2, 1, 1, 3, 1, 0, 4, 0, 3, 3, 4, 4, 1, 4, 3, 0, 2])

In [ ]:
np.unique(Y_train)

array([0, 1, 2, 3, 4])

In [ ]:
len(np.unique(Y_train))

5

In [ ]:
unique, counts = np.unique(Y_train, return_counts=True)
print(unique)
print(counts)

[0 1 2 3 4]
[22 19 38 36 17]


In [ ]:
max(X_train, key=len)

'I am so impressed by your dedication to this project'

In [ ]:
max(X_train, key=len).split(" ")

['I',
 'am',
 'so',
 'impressed',
 'by',
 'your',
 'dedication',
 'to',
 'this',
 'project']

In [ ]:
max_len = len(max(X_train, key=len).split(" "))
max_len

10

In [ ]:
!wget https://nlp.stanford.edu/data/glove.6B.zip

--2025-05-11 07:35:03--  https://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2025-05-11 07:35:03--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6B.zip        100%[===================>] 822.24M  5.01MB/s    in 2m 38s  

2025-05-11 07:37:42 (5.19 MB/s) - ‘glove.6B.zip’ saved [862182613/862182613]



In [ ]:
!unzip -q glove.6B.zip -d glove.6B

In [ ]:
f = open("/content/glove.6B/glove.6B.50d.txt", encoding="utf-8")

word_vectors = {}
for line in f:
    line = line.strip().split()
    word = line[0]
    vector = np.array(line[1:], dtype=np.float64)
    word_vectors[word] = vector

In [ ]:
word_vectors["love"]

array([-0.13886  ,  1.1401   , -0.85212  , -0.29212  ,  0.75534  ,
        0.82762  , -0.3181   ,  0.0072204, -0.34762  ,  1.0731   ,
       -0.24665  ,  0.97765  , -0.55835  , -0.090318 ,  0.83182  ,
       -0.33317  ,  0.22648  ,  0.30913  ,  0.026929 , -0.086739 ,
       -0.14703  ,  1.3543   ,  0.53695  ,  0.43735  ,  1.2749   ,
       -1.4382   , -1.2815   , -0.15196  ,  1.0506   , -0.93644  ,
        2.7561   ,  0.58967  , -0.29473  ,  0.27574  , -0.32928  ,
       -0.201    , -0.28547  , -0.45987  , -0.14603  , -0.69372  ,
        0.070761 , -0.19326  , -0.1855   , -0.16095  ,  0.24268  ,
        0.20784  ,  0.030924 , -1.3711   , -0.28606  ,  0.2898   ])

In [ ]:
def sentence_to_avg(sentence):
    try:
        sentence = sentence.lower()
        words = sentence.strip().split(" ")

        sum_vectors = np.zeros((50, ))
        for word in words:
            sum_vectors += word_vectors[word]

        avg_vector = sum_vectors / len(words)
        return avg_vector
    except:
        print(sentence)
        return None

In [ ]:
sentence_to_avg("I love programming very much")

array([ 0.21402   ,  0.24146912, -0.3219846 , -0.169208  ,  0.483176  ,
        0.2192604 , -0.3905278 , -0.20376192, -0.497238  ,  0.51688151,
        0.015846  ,  0.521284  , -0.351054  , -0.0542684 ,  0.5911438 ,
        0.340718  ,  0.142232  ,  0.455954  , -0.05321598, -0.5421058 ,
       -0.166728  ,  0.654546  ,  0.47333   ,  0.370588  ,  0.888124  ,
       -1.438646  , -0.8024356 ,  0.260028  ,  0.775556  , -0.409289  ,
        3.43296   ,  0.409712  , -0.0329154 , -0.326434  , -0.1459134 ,
       -0.128366  , -0.1091386 ,  0.288342  , -0.198344  , -0.312754  ,
        0.03890534,  0.1295664 , -0.317196  ,  0.346144  , -0.2118628 ,
        0.1564436 ,  0.0284948 , -0.17581332, -0.294982  ,  0.748832  ])

In [ ]:
X_train_avg = []

for x_train in X_train:
    X_train_avg.append(sentence_to_avg(x_train))

X_train_avg = np.array(X_train_avg)

In [ ]:
X_train_avg.shape

(132, 50)